(define (extract-labels text)
  (if (null? text)
      (cons '() '())
      (let* ((result (extract-labels (cdr text)))
             (insts (car result))
             (labels (cdr result))
             (next-inst (car text)))
        (if (symbol? next-inst)
            (begin (set! insts (cons (make-instruction-with-label (instruction-text (car insts)) next-inst) 
                                     (cdr insts)))
                   (cons insts (cons (make-label-entry next-inst insts) labels)))
            (cons (cons (make-instruction next-inst) insts) labels)))))
